version: '3'

services:
  app:
    build: .
    environment:
      COUCHDB_HOST: couchdb
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DB: ${COUCHDB_DB}
      AMQP_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy

  couchdb:
    image: couchdb:latest
#    volumes:
#      - couchdb-data:/opt/couchdb/data
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 2s
      timeout: 30s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 30s
      retries: 10