version: '3'

services:
  app:
    build: .
    environment:
      COUCHDB_HOST: couchdb
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DB: ${COUCHDB_DB}
      AMQP_HOST: rabbitmq

  couchdb:
    image: couchdb:latest
    volumes:
      - couchdb-data:/opt/couchdb/data
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  couchdb-data:
